name = "PublicJuliaRegistry"
uuid = "84f33253-0491-444a-bf7b-6508e99dde09"
repo = "https://github.com/RoyCCWang/PublicJuliaRegistry"
description = "Public unregistered Julia packages"

[packages]
c16f81ae-bc18-4c85-8dee-b67f3150a483 = { name = "Utilities", path = "U/Utilities" }
